# Generated by Django 4.2.6 on 2023-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0003_delete_ajax_delete_csvupload_alter_document_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
