# Generated by Django 4.2.6 on 2023-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0005_alter_document_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
